//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AltTab.rc
//
#define IDD_ALTTAB_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_ALTTAB                      107
#define IDC_ALTTAB                      109
#define IDR_MAINFRAME                   128
#define IDC_TRAY_CONTEXTMENU            129
#define IDD_SETTINGS                    130
#define IDR_CONTEXTMENU                 131
#define IDD_CHECK_FOR_UPDATES           132
#define IDC_LISTVIEW                    1001
#define IDC_SYSLINK_COPYRIGHT           1002
#define IDC_EDIT_SETTINGS_FILEPATH      1005
#define IDC_EDIT_SIMILAR_PROCESS_GROUPS 1006
#define IDC_EDIT_PROCESS_EXCLUSIONS     1007
#define IDC_CHECK_PROMPT_TERMINATE_ALL  1008
#define IDC_CHECK_PROCESS_EXCLUSIONS    1009
#define IDC_EDIT_FUZZY_MATCH_PERCENT    1010
#define IDC_SPIN_FUZZY_MATCH_PERCENT    1011
#define IDC_CHECK_FOR_UPDATES           1012
#define IDC_BUTTON_APPLY                1013
#define IDC_SYSLINK_ABOUT_PRODUCT_NAME  1014
#define IDC_SYSLINK_ABOUT_COPYRIGHT     1015
#define IDC_EDIT_WINDOW_TRANSPARENCY    1016
#define IDC_SPIN_WINDOW_TRANSPARENCY    1017
#define IDC_EDIT_WINDOW_WIDTH_PERCENTAGE 1018
#define IDC_SPIN_WINDOW_WIDTH_PERCENTAGE 1019
#define IDC_EDIT_WINDOW_HEIGHT_PERCENTAGE 1020
#define IDC_SPIN_WINDOW_HEIGHT_PERCENTAGE 1021
#define IDC_BUTTON_RESET                1022
#define IDC_CHECK_SHOW_COL_HEADER       1023
#define IDC_CHECK_SHOW_COL_PROCESSNAME  1024
#define IDC_CHECK_SHOW_SEARCH_STRING    1025
#define IDC_STATIC_FUZZY_MATCH_PERCENT  1026
#define IDC_GROUP_PROCESS_EXCLUSIONS    1027
#define IDC_EDIT_CFU_CHANGES            1028
#define IDC_CHECK_ALT_CTRL_TAB          1028
#define IDC_STATIC_CFU_CURRENT_VERSION  1029
#define IDC_BUTTON_RELOAD               1029
#define IDC_STATIC_CFU_UPDATE_VERSION   1030
#define IDC_CHECK_ALT_BACKTICK          1030
#define IDC_STATIC_1                    1031
#define IDC_CHECK_ALT_TAB               1031
#define IDC_STATIC_2                    1032
#define IDC_CHECK_SHOW_PROCESSINFO_TOOLTIP 1032
#define IDC_STATIC_3                    1033
#define IDC_GROUPBOX_STORAGE            1034
#define ID_TRAYCONTEXTMENU_ABOUTALTTAB  32771
#define ID_TRAYCONTEXTMENU_README       32772
#define ID_TRAYCONTEXTMENU_HELP         32773
#define ID_TRAYCONTEXTMENU_RELEASENOTES 32774
#define ID_TRAYCONTEXTMENU_SETTINGS     32775
#define ID_TRAYCONTEXTMENU_DISABLEALTTAB 32776
#define ID_TRAYCONTEXTMENU_CHECKFORUPDATES 32777
#define ID_TRAYCONTEXTMENU_RUNATSTARTUP 32778
#define ID_TRAYCONTEXTMENU_EXIT         32779
#define ID_TRAYCONTEXTMENU_RESTART      32781
#define ID_CONTEXTMENU_TERMINATE        32782
#define ID_CONTEXTMENU_KILL             32783
#define ID_CONTEXTMENU_CLOSEALLWINDOWS  32784
#define ID_CONTEXTMENU_KILLALLPROCESSES 32785
#define ID_CONTEXTMENU_EXIT             32786
#define ID_CONTEXTMENU_ABOUALTTAB       32787
#define ID_CONTEXTMENU_SETTINGS         32788
#define ID_CONTEXTMENU_KILL_PROCESS     32789
#define ID_CONTEXTMENU_CLOSE_WINDOW     32790
#define ID_CONTEXTMENU_ABOUTALTTAB      32791
#define ID_Menu                         32793
#define ID_CONTEXTMENU_OPEN_PATH        32794
#define ID_CONTEXTMENU_COPY_PATH        32795
#define ID_TRAYCONTEXTMENU_RELOADALTTABSETTINGS 32796
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
